[package]
name = "clone"
version = "0.1.0"
edition = "2018"
build = "build.rs"

[dependencies]
sdl2 = "0.34.5"
gl = {path = "lib/gl"}
cgmath = "0.18.0"
c_str_macro = "1.0.3"
imgui = "0.7.0"
imgui-sdl2 = "0.14.0"
imgui-opengl-renderer = "0.11.0"
image = "0.23.14"